services:
  mongo:
    image: mongo:7
    container_name: dta_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: decision_theory
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dta_backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "decision_theory"
    depends_on:
      - mongo

volumes:
  mongo_data:
